import Hero from "components/Hero";
import About from "components/About";
import ProjectsList from "components/ProjectsList";
import Head from "next/head";
import NavBar from "../components/NavBar";
import TechtimonialsList from "components/TechtimonialsList";
import { techtimonialsArray } from "components/TechtimonialsList/techtimonialsArray";
import { SocialLinksBottom } from "./styles";

export default function Home() {
  return (
    <div>
      <Head>
        <title>cmz.codes - fullstack developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <NavBar />
      <Hero />
      <About />
      <ProjectsList />
      <TechtimonialsList list={techtimonialsArray} />
      <SocialLinksBottom />
      <NavBar />
    </div>
  );
}
